name: Publish
on:
  push:
    tags:
      - v*.*.*

  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: smartsquaregmbh/delete-old-packages@v0.3.3
      with:
        keep: 10
        names: |
          ChemSharp
          ChemSharp.Spectroscopy
          ChemSharp.Molecules
          ChemSharp.Molecules.Blazor
          ChemSharp.UnitConversion    
          ChemSharp.Rendering
    - uses: actions/checkout@v2  
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x 
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Install dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -o tmp
    - run: cd ../
    - name: publish nuget
      run: dotnet nuget push tmp\*.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json  
    - name: publish github
      run: dotnet nuget push tmp\*.nupkg --skip-duplicate --no-symbols true -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/JensKrumsieck/index.json 
